apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripay-ingress
  namespace: tripay
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pay.tripay.com.tr
      secretName: tripay-tls
  rules:
    - host: pay.tripay.com.tr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tripay-web
                port:
                  number: 80
